const data = [
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Basics of Programming",
    text: [
      "1. C++ Basic CWH 1 - 20",
      "2. I/O , Conditional Statements",
      "3. Loops, Pointers",
      "4. Array, String",
      "5. Functions",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Time and space complexity",
    text: [
      "1. Time Complexity",
      "2. Space Complexity",
      "3. Asymptotic Notation",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "STL",
    text: [
      "1. Vectors and Pairs",
      "2. Maps and Set",
      "3. Stack , Queue ,Dequeue and Priority-Queue",
      "4. STL algorithms",
      "5. Sorting and Comparator Function ",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Array's Algorithms",
    text: [
      "1. Kadane's Algorithm",
      "2. Sliding Window",
      "3. Dutch National Flag Algorithm",
      "4. Searching and Sorting",
      "5. Prefix and Suffix sum",
      "6. Two Pointer",
      "7. 2D Array"
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "String's Algorithm",
    text: [
      "1. KMP Algorithm",
      "2. Rabin Karp Algorithm",
      "3. Z-Algorithm",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Greedy Algorithm",
    text: [
      "1. Activity Selection Problems",
      "2. Egyptian Problems",
      "3. Job Sequencing",
      "4. Minimum Swaps for Bracket Balancing",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Binary Search",
    text: [
      "1. Binary Search I ",
      "2. Binary Search II",
      "3. Binary Search III",
      "4. Ternary Search",
    ],
  },  
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Number Theory",
    text: [
      "1. Euclid's GCD algorithm and Extended Euclid algorithm",
      "2. Basic Modular Arithmetic",
      "3. Modular Exponentiation",
      "4. Modular Inverse",
      "5. Prime Factorization of a number",
     " 6. Sieve of Eratosthenes",
      "7. Segmented Sieve",
      "8. Euler Totient Function",
      "9. Fermat's Little Theorem",
      "10. NCR mod p calculation",
      "11. Lucas Theorem",
      "12. Chinese Remainder Theorem",
      "13. Mobius Function",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Recursion and Backtracking",
    text: [
      "1. Recursion and Backtracking Basics",
      "2. Subset Sum",
      "3.  Combination Sum",
      "4.	N queens Problem",
      "5. Sudoku Solver",
      "6. Rat in a Maze",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Bit Manipulation",
    text: [
      "1. Bitwise Operators",
      "2. Bit Masking",
      "3. Binary Exponentiation",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Dynamic Programming",
    text: [
      "1. Introduction",
      "2. Digit DP",
      "3. DP on Trees",
      "4. DP with Bitmask",
      "5. SOS DP",
      "6. Beginner to Advanced",
      "7. Non Trivial DP Tricks and Techniques",
      "8. CF Blog",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Graph",
    text: 
    [
      "1. Graph Representation",
      "2. DFS",
      "3. BFS",
      "4. Dijkstras's Algorithm",
      "5. Bellman Ford Algorithm",
      "6. Bridges",
      "7. Articulation Points",
      "8. Topological Sort",
      "9. Strongly Connected Components(SCC)",
      "10. Tarjan's Algorithm for SCC",
      "11. Kruskal's Algorithm",
      "12. Prims's Algorithm",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Tree",
    text: [
      "1. Traversal Techniques",
      "2. Binary Tree, BST, Balanced Binary Tree",
      "3. Binary Lifting",
      "4. Bridges, BridgeTree, Cutpoits, SCC, DFS Tree",
      "5. Dynamic Programming on tree",
      "6. 2K Decomposition of tree (and Lowest Common Ancestor)",
      "7. Kruskal Reconstruction Tree (KRT) (IOI Werewolf trick)",
      "8. Set Merging (with linear height merging)",
      "9. O(N2) Distribution DP",
      "10. 'Re-rooting' tree DP (where you DP twice, once going down and once propagating from top)",
      "11. Centroid Decomposition",
      "12. Heavy-Light Decomposition",
      "13. UFDS on tree (See: CEOI 2017 Streets)",
    ],
  },
  {
    date: "",
    img: "/src/Components/Roadmap/Image/CPSOC1.jpg",
    header: "Miscellaneous Topics",
    text: [
      "1. Segment Tree & Fenwick Tree",
      "2. Game Thoery",
      "3. Probability & Expectation",
      "4. Matrix Exponention",
      "5. Euler Tour",
      "6. Trie"
    ],
  },
];

export default data;

